// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package bus_sniffer_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 5;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    struct packed {logic q;} en;
    struct packed {logic q;} rst_fifo;
    struct packed {logic q;} frame_read;
    struct packed {logic q;} enable_gating;
  } bus_sniffer_reg2hw_sni_ctrl_reg_t;

  typedef struct packed {
    struct packed {logic q;} empty;
    struct packed {logic q;} full;
    struct packed {logic q;} frame_avail;
  } bus_sniffer_reg2hw_sni_status_reg_t;

  typedef struct packed {logic [31:0] q;} bus_sniffer_reg2hw_sni_data0_reg_t;

  typedef struct packed {logic [31:0] q;} bus_sniffer_reg2hw_sni_data1_reg_t;

  typedef struct packed {logic [31:0] q;} bus_sniffer_reg2hw_sni_data2_reg_t;

  typedef struct packed {logic [31:0] q;} bus_sniffer_reg2hw_sni_data3_reg_t;

  typedef struct packed {
    struct packed {
      logic d;
      logic de;
    } empty;
    struct packed {
      logic d;
      logic de;
    } full;
    struct packed {
      logic d;
      logic de;
    } frame_avail;
  } bus_sniffer_hw2reg_sni_status_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } bus_sniffer_hw2reg_sni_data0_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } bus_sniffer_hw2reg_sni_data1_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } bus_sniffer_hw2reg_sni_data2_reg_t;

  typedef struct packed {
    logic [31:0] d;
    logic        de;
  } bus_sniffer_hw2reg_sni_data3_reg_t;

  // Register -> HW type
  typedef struct packed {
    bus_sniffer_reg2hw_sni_ctrl_reg_t   sni_ctrl;    // [134:131]
    bus_sniffer_reg2hw_sni_status_reg_t sni_status;  // [130:128]
    bus_sniffer_reg2hw_sni_data0_reg_t  sni_data0;   // [127:96]
    bus_sniffer_reg2hw_sni_data1_reg_t  sni_data1;   // [95:64]
    bus_sniffer_reg2hw_sni_data2_reg_t  sni_data2;   // [63:32]
    bus_sniffer_reg2hw_sni_data3_reg_t  sni_data3;   // [31:0]
  } bus_sniffer_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    bus_sniffer_hw2reg_sni_status_reg_t sni_status;  // [137:132]
    bus_sniffer_hw2reg_sni_data0_reg_t  sni_data0;   // [131:99]
    bus_sniffer_hw2reg_sni_data1_reg_t  sni_data1;   // [98:66]
    bus_sniffer_hw2reg_sni_data2_reg_t  sni_data2;   // [65:33]
    bus_sniffer_hw2reg_sni_data3_reg_t  sni_data3;   // [32:0]
  } bus_sniffer_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] BUS_SNIFFER_SNI_CTRL_OFFSET = 5'h0;
  parameter logic [BlockAw-1:0] BUS_SNIFFER_SNI_STATUS_OFFSET = 5'h4;
  parameter logic [BlockAw-1:0] BUS_SNIFFER_SNI_DATA0_OFFSET = 5'h8;
  parameter logic [BlockAw-1:0] BUS_SNIFFER_SNI_DATA1_OFFSET = 5'hc;
  parameter logic [BlockAw-1:0] BUS_SNIFFER_SNI_DATA2_OFFSET = 5'h10;
  parameter logic [BlockAw-1:0] BUS_SNIFFER_SNI_DATA3_OFFSET = 5'h14;

  // Register index
  typedef enum int {
    BUS_SNIFFER_SNI_CTRL,
    BUS_SNIFFER_SNI_STATUS,
    BUS_SNIFFER_SNI_DATA0,
    BUS_SNIFFER_SNI_DATA1,
    BUS_SNIFFER_SNI_DATA2,
    BUS_SNIFFER_SNI_DATA3
  } bus_sniffer_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] BUS_SNIFFER_PERMIT[6] = '{
      4'b0001,  // index[0] BUS_SNIFFER_SNI_CTRL
      4'b0001,  // index[1] BUS_SNIFFER_SNI_STATUS
      4'b1111,  // index[2] BUS_SNIFFER_SNI_DATA0
      4'b1111,  // index[3] BUS_SNIFFER_SNI_DATA1
      4'b1111,  // index[4] BUS_SNIFFER_SNI_DATA2
      4'b1111  // index[5] BUS_SNIFFER_SNI_DATA3
  };

endpackage

