// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Top module auto-generated by `reggen`


`include "common_cells/assertions.svh"

module bus_sniffer_reg_top #(
    parameter type reg_req_t = logic,
    parameter type reg_rsp_t = logic,
    parameter int AW = 5
) (
    input logic clk_i,
    input logic rst_ni,
    input reg_req_t reg_req_i,
    output reg_rsp_t reg_rsp_o,
    // To HW
    output bus_sniffer_reg_pkg::bus_sniffer_reg2hw_t reg2hw,  // Write
    input bus_sniffer_reg_pkg::bus_sniffer_hw2reg_t hw2reg,  // Read


    // Config
    input devmode_i  // If 1, explicit error return for unmapped register access
);

  import bus_sniffer_reg_pkg::*;

  localparam int DW = 32;
  localparam int DBW = DW / 8;  // Byte Width

  // register signals
  logic           reg_we;
  logic           reg_re;
  logic [ AW-1:0] reg_addr;
  logic [ DW-1:0] reg_wdata;
  logic [DBW-1:0] reg_be;
  logic [ DW-1:0] reg_rdata;
  logic           reg_error;

  logic addrmiss, wr_err;

  logic [DW-1:0] reg_rdata_next;

  // Below register interface can be changed
  reg_req_t reg_intf_req;
  reg_rsp_t reg_intf_rsp;


  assign reg_intf_req = reg_req_i;
  assign reg_rsp_o = reg_intf_rsp;


  assign reg_we = reg_intf_req.valid & reg_intf_req.write;
  assign reg_re = reg_intf_req.valid & ~reg_intf_req.write;
  /* verilator lint_off WIDTH */
  assign reg_addr = reg_intf_req.addr;
  assign reg_wdata = reg_intf_req.wdata;
  assign reg_be = reg_intf_req.wstrb;
  assign reg_intf_rsp.rdata = reg_rdata;
  assign reg_intf_rsp.error = reg_error;
  assign reg_intf_rsp.ready = 1'b1;

  assign reg_rdata = reg_rdata_next;
  assign reg_error = (devmode_i & addrmiss) | wr_err;


  // Define SW related signals
  // Format: <reg>_<field>_{wd|we|qs}
  //        or <reg>_{wd|we|qs} if field == 1 or 0
  logic sni_ctrl_en_qs;
  logic sni_ctrl_en_wd;
  logic sni_ctrl_en_we;
  logic sni_ctrl_rst_fifo_qs;
  logic sni_ctrl_rst_fifo_wd;
  logic sni_ctrl_rst_fifo_we;
  logic sni_ctrl_frame_read_qs;
  logic sni_ctrl_frame_read_wd;
  logic sni_ctrl_frame_read_we;
  logic sni_ctrl_enable_gating_qs;
  logic sni_ctrl_enable_gating_wd;
  logic sni_ctrl_enable_gating_we;
  logic sni_ctrl_dpi_en_qs;
  logic sni_ctrl_dpi_en_wd;
  logic sni_ctrl_dpi_en_we;
  logic sni_status_empty_qs;
  logic sni_status_full_qs;
  logic sni_status_frame_avail_qs;
  logic [31:0] sni_data0_qs;
  logic [31:0] sni_data1_qs;
  logic [31:0] sni_data2_qs;
  logic [31:0] sni_data3_qs;

  // Register instances
  // R[sni_ctrl]: V(False)

  //   F[en]: 0:0
  prim_subreg #(
      .DW      (1),
      .SWACCESS("RW"),
      .RESVAL  (1'h0)
  ) u_sni_ctrl_en (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(sni_ctrl_en_we),
      .wd(sni_ctrl_en_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.sni_ctrl.en.q),

      // to register interface (read)
      .qs(sni_ctrl_en_qs)
  );


  //   F[rst_fifo]: 1:1
  prim_subreg #(
      .DW      (1),
      .SWACCESS("RW"),
      .RESVAL  (1'h0)
  ) u_sni_ctrl_rst_fifo (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(sni_ctrl_rst_fifo_we),
      .wd(sni_ctrl_rst_fifo_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.sni_ctrl.rst_fifo.q),

      // to register interface (read)
      .qs(sni_ctrl_rst_fifo_qs)
  );


  //   F[frame_read]: 2:2
  prim_subreg #(
      .DW      (1),
      .SWACCESS("RW"),
      .RESVAL  (1'h0)
  ) u_sni_ctrl_frame_read (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(sni_ctrl_frame_read_we),
      .wd(sni_ctrl_frame_read_wd),

      // from internal hardware
      .de(hw2reg.sni_ctrl.frame_read.de),
      .d (hw2reg.sni_ctrl.frame_read.d),

      // to internal hardware
      .qe(),
      .q (reg2hw.sni_ctrl.frame_read.q),

      // to register interface (read)
      .qs(sni_ctrl_frame_read_qs)
  );


  //   F[enable_gating]: 3:3
  prim_subreg #(
      .DW      (1),
      .SWACCESS("RW"),
      .RESVAL  (1'h0)
  ) u_sni_ctrl_enable_gating (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(sni_ctrl_enable_gating_we),
      .wd(sni_ctrl_enable_gating_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.sni_ctrl.enable_gating.q),

      // to register interface (read)
      .qs(sni_ctrl_enable_gating_qs)
  );


  //   F[dpi_en]: 4:4
  prim_subreg #(
      .DW      (1),
      .SWACCESS("RW"),
      .RESVAL  (1'h1)
  ) u_sni_ctrl_dpi_en (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      // from register interface
      .we(sni_ctrl_dpi_en_we),
      .wd(sni_ctrl_dpi_en_wd),

      // from internal hardware
      .de(1'b0),
      .d ('0),

      // to internal hardware
      .qe(),
      .q (reg2hw.sni_ctrl.dpi_en.q),

      // to register interface (read)
      .qs(sni_ctrl_dpi_en_qs)
  );


  // R[sni_status]: V(False)

  //   F[empty]: 0:0
  prim_subreg #(
      .DW      (1),
      .SWACCESS("RO"),
      .RESVAL  (1'h0)
  ) u_sni_status_empty (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      .we(1'b0),
      .wd('0),

      // from internal hardware
      .de(hw2reg.sni_status.empty.de),
      .d (hw2reg.sni_status.empty.d),

      // to internal hardware
      .qe(),
      .q (reg2hw.sni_status.empty.q),

      // to register interface (read)
      .qs(sni_status_empty_qs)
  );


  //   F[full]: 1:1
  prim_subreg #(
      .DW      (1),
      .SWACCESS("RO"),
      .RESVAL  (1'h0)
  ) u_sni_status_full (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      .we(1'b0),
      .wd('0),

      // from internal hardware
      .de(hw2reg.sni_status.full.de),
      .d (hw2reg.sni_status.full.d),

      // to internal hardware
      .qe(),
      .q (reg2hw.sni_status.full.q),

      // to register interface (read)
      .qs(sni_status_full_qs)
  );


  //   F[frame_avail]: 2:2
  prim_subreg #(
      .DW      (1),
      .SWACCESS("RO"),
      .RESVAL  (1'h0)
  ) u_sni_status_frame_avail (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      .we(1'b0),
      .wd('0),

      // from internal hardware
      .de(hw2reg.sni_status.frame_avail.de),
      .d (hw2reg.sni_status.frame_avail.d),

      // to internal hardware
      .qe(),
      .q (reg2hw.sni_status.frame_avail.q),

      // to register interface (read)
      .qs(sni_status_frame_avail_qs)
  );


  // R[sni_data0]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RO"),
      .RESVAL  (32'h0)
  ) u_sni_data0 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      .we(1'b0),
      .wd('0),

      // from internal hardware
      .de(hw2reg.sni_data0.de),
      .d (hw2reg.sni_data0.d),

      // to internal hardware
      .qe(),
      .q (reg2hw.sni_data0.q),

      // to register interface (read)
      .qs(sni_data0_qs)
  );


  // R[sni_data1]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RO"),
      .RESVAL  (32'h0)
  ) u_sni_data1 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      .we(1'b0),
      .wd('0),

      // from internal hardware
      .de(hw2reg.sni_data1.de),
      .d (hw2reg.sni_data1.d),

      // to internal hardware
      .qe(),
      .q (reg2hw.sni_data1.q),

      // to register interface (read)
      .qs(sni_data1_qs)
  );


  // R[sni_data2]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RO"),
      .RESVAL  (32'h0)
  ) u_sni_data2 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      .we(1'b0),
      .wd('0),

      // from internal hardware
      .de(hw2reg.sni_data2.de),
      .d (hw2reg.sni_data2.d),

      // to internal hardware
      .qe(),
      .q (reg2hw.sni_data2.q),

      // to register interface (read)
      .qs(sni_data2_qs)
  );


  // R[sni_data3]: V(False)

  prim_subreg #(
      .DW      (32),
      .SWACCESS("RO"),
      .RESVAL  (32'h0)
  ) u_sni_data3 (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      .we(1'b0),
      .wd('0),

      // from internal hardware
      .de(hw2reg.sni_data3.de),
      .d (hw2reg.sni_data3.d),

      // to internal hardware
      .qe(),
      .q (reg2hw.sni_data3.q),

      // to register interface (read)
      .qs(sni_data3_qs)
  );




  logic [5:0] addr_hit;
  always_comb begin
    addr_hit = '0;
    addr_hit[0] = (reg_addr == BUS_SNIFFER_SNI_CTRL_OFFSET);
    addr_hit[1] = (reg_addr == BUS_SNIFFER_SNI_STATUS_OFFSET);
    addr_hit[2] = (reg_addr == BUS_SNIFFER_SNI_DATA0_OFFSET);
    addr_hit[3] = (reg_addr == BUS_SNIFFER_SNI_DATA1_OFFSET);
    addr_hit[4] = (reg_addr == BUS_SNIFFER_SNI_DATA2_OFFSET);
    addr_hit[5] = (reg_addr == BUS_SNIFFER_SNI_DATA3_OFFSET);
  end

  assign addrmiss = (reg_re || reg_we) ? ~|addr_hit : 1'b0;

  // Check sub-word write is permitted
  always_comb begin
    wr_err = (reg_we &
              ((addr_hit[0] & (|(BUS_SNIFFER_PERMIT[0] & ~reg_be))) |
               (addr_hit[1] & (|(BUS_SNIFFER_PERMIT[1] & ~reg_be))) |
               (addr_hit[2] & (|(BUS_SNIFFER_PERMIT[2] & ~reg_be))) |
               (addr_hit[3] & (|(BUS_SNIFFER_PERMIT[3] & ~reg_be))) |
               (addr_hit[4] & (|(BUS_SNIFFER_PERMIT[4] & ~reg_be))) |
               (addr_hit[5] & (|(BUS_SNIFFER_PERMIT[5] & ~reg_be)))));
  end

  assign sni_ctrl_en_we = addr_hit[0] & reg_we & !reg_error;
  assign sni_ctrl_en_wd = reg_wdata[0];

  assign sni_ctrl_rst_fifo_we = addr_hit[0] & reg_we & !reg_error;
  assign sni_ctrl_rst_fifo_wd = reg_wdata[1];

  assign sni_ctrl_frame_read_we = addr_hit[0] & reg_we & !reg_error;
  assign sni_ctrl_frame_read_wd = reg_wdata[2];

  assign sni_ctrl_enable_gating_we = addr_hit[0] & reg_we & !reg_error;
  assign sni_ctrl_enable_gating_wd = reg_wdata[3];

  assign sni_ctrl_dpi_en_we = addr_hit[0] & reg_we & !reg_error;
  assign sni_ctrl_dpi_en_wd = reg_wdata[4];

  // Read data return
  always_comb begin
    reg_rdata_next = '0;
    unique case (1'b1)
      addr_hit[0]: begin
        reg_rdata_next[0] = sni_ctrl_en_qs;
        reg_rdata_next[1] = sni_ctrl_rst_fifo_qs;
        reg_rdata_next[2] = sni_ctrl_frame_read_qs;
        reg_rdata_next[3] = sni_ctrl_enable_gating_qs;
        reg_rdata_next[4] = sni_ctrl_dpi_en_qs;
      end

      addr_hit[1]: begin
        reg_rdata_next[0] = sni_status_empty_qs;
        reg_rdata_next[1] = sni_status_full_qs;
        reg_rdata_next[2] = sni_status_frame_avail_qs;
      end

      addr_hit[2]: begin
        reg_rdata_next[31:0] = sni_data0_qs;
      end

      addr_hit[3]: begin
        reg_rdata_next[31:0] = sni_data1_qs;
      end

      addr_hit[4]: begin
        reg_rdata_next[31:0] = sni_data2_qs;
      end

      addr_hit[5]: begin
        reg_rdata_next[31:0] = sni_data3_qs;
      end

      default: begin
        reg_rdata_next = '1;
      end
    endcase
  end

  // Unused signal tieoff

  // wdata / byte enable are not always fully used
  // add a blanket unused statement to handle lint waivers
  logic unused_wdata;
  logic unused_be;
  assign unused_wdata = ^reg_wdata;
  assign unused_be = ^reg_be;

  // Assertions for Register Interface
  `ASSERT(en2addrHit, (reg_we || reg_re) |-> $onehot0(addr_hit))

endmodule

/* verilator lint_off DECLFILENAME */
module bus_sniffer_reg_top_intf #(
    parameter  int AW = 5,
    localparam int DW = 32
) (
    input logic clk_i,
    input logic rst_ni,
    REG_BUS.in regbus_slave,
    // To HW
    output bus_sniffer_reg_pkg::bus_sniffer_reg2hw_t reg2hw,  // Write
    input bus_sniffer_reg_pkg::bus_sniffer_hw2reg_t hw2reg,  // Read
    // Config
    input devmode_i  // If 1, explicit error return for unmapped register access
);
  localparam int unsigned STRB_WIDTH = DW / 8;

  `include "register_interface/typedef.svh"
  `include "register_interface/assign.svh"

  // Define structs for reg_bus
  typedef logic [AW-1:0] addr_t;
  typedef logic [DW-1:0] data_t;
  typedef logic [STRB_WIDTH-1:0] strb_t;
  `REG_BUS_TYPEDEF_ALL(reg_bus, addr_t, data_t, strb_t)

  reg_bus_req_t s_reg_req;
  reg_bus_rsp_t s_reg_rsp;

  // Assign SV interface to structs
  `REG_BUS_ASSIGN_TO_REQ(s_reg_req, regbus_slave)
  `REG_BUS_ASSIGN_FROM_RSP(regbus_slave, s_reg_rsp)



  bus_sniffer_reg_top #(
      .reg_req_t(reg_bus_req_t),
      .reg_rsp_t(reg_bus_rsp_t),
      .AW(AW)
  ) i_regs (
      .clk_i,
      .rst_ni,
      .reg_req_i(s_reg_req),
      .reg_rsp_o(s_reg_rsp),
      .reg2hw,  // Write
      .hw2reg,  // Read
      .devmode_i
  );

endmodule


